FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends curl \
  && rm -rf /var/lib/apt/lists/*
  
COPY .mvn/ .mvn/
COPY mvnw pom.xml ./

RUN chmod +x mvnw

RUN ./mvnw dependency:go-offline -B

COPY src/ src/

EXPOSE 8080

CMD ["./mvnw", "spring-boot:run"]